model_params: 
  engine: "gpt-3.5-turbo-instruct"
  temperature: 0.25
  max_tokens: 500
  top_p: 1
  frequency_penalty: 0.3
input_csv: "./input/email_list.csv"
template_email_path: "./input/email_template.txt"
output_path: "./output/example_output.txt"